profiler:
  target: dev
  outputs:
    dev:
      type: mysql
      server: "{{env_var('MYSQL_HOST')}}"
      port: "{{env_var('MYSQL_PORT') | int}}"
      database: dbt_profiler
      schema: dbt_profiler
      username: "{{env_var('MYSQL_USER')}}"
      password: "{{env_var('MYSQL_PWD')}}"
      ssl_disabled: True
      charset: "utf8mb4"